# Main Hyprlock config.
# Split config files live in ~/.config/hypr/conf.d/hyprlock.d/.

source = ~/.config/hypr/conf.d/hyprlock.d/variables.conf
source = ~/.config/hypr/conf.d/hyprlock.d/general.conf
source = ~/.config/hypr/conf.d/hyprlock.d/animations.conf
source = ~/.config/hypr/conf.d/hyprlock.d/background.conf
source = ~/.config/hypr/conf.d/hyprlock.d/input.conf
source = ~/.config/hypr/conf.d/hyprlock.d/labels.conf
