# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = us
    kb_variant =
    kb_model =
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    # Tablet settings for 2560x1080 monitor with CTL-472 tablet, centered
    tablet {
        # output = DP-1
        # relative_input = true
        region_position = 416 0
        region_size = 1728 1080
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
}
