# Layer Rules
#layerrule = blur, notifications
#layerrule = ignorezero, notifications
#layerrule = blur, launcher
#layerrule = ignorezero, launcher

# Window Rules
# pinned window style
windowrulev = bordercolor rgb(598da8) rgb(598da8), pinned:1
# windowrulev2 = float,class:(.*)
windowrulev = tile,class:(Alacritty)
windowrulev = float,title:(Volume Control) # Volume Control
windowrulev = float,class:(steam) # Steam Popups
windowrulev = float,title:(Qt5 Configuration Tool) # Qt5
windowrulev = float,title:(Qt6 Configuration Tool) # Qt6
windowrulev = float,title:(Fcitx Configuration) # Fcitx Config
windowrulev = float,class:(vlc) # VLC Popups
windowrulev = float,class:(qemu.*) # QEMU
windowrulev = float,class:(org.telegram.desktop),title:(Media viewer)
windowrulev = float,class:(com.st.app.Main)
windowrulev = float,class:(ltspice.exe)
# always render
windowrulev = renderunfocused,class:(vseeface.exe)
# immediate render
windowrulev = immediate, class:^(cs2)$
