# Time
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = 0, 220
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font

    position = 0, 330
    halign = center
    valign = center
}
