# Auto start
exec-once = hyprlock
exec-once = hyprpaper
exec-once = qs
exec-once = fcitx5
# exec-once = swayidle timeout 300 'hyprctl dispatcher dpms off'
exec-once = dbus-update-activation-environment --systemd --all

# Agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1
