$fileManager = dolphin
$Browser = google-chrome

# Variables
$proxy_socks5 = socks5://localhost:7891
$proxy_http = http://localhost:7890

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
