# Main Hyprland config.
# Split config files live in ~/.config/hypr/conf.d/hyprland.d/.

source = ~/.config/hypr/conf.d/hyprland.d/monitors.conf
source = ~/.config/hypr/conf.d/hyprland.d/env.conf
source = ~/.config/hypr/conf.d/hyprland.d/input.conf
source = ~/.config/hypr/conf.d/hyprland.d/layout.conf
source = ~/.config/hypr/conf.d/hyprland.d/rules.conf
source = ~/.config/hypr/conf.d/hyprland.d/variables.conf
source = ~/.config/hypr/conf.d/hyprland.d/binds.conf
source = ~/.config/hypr/conf.d/hyprland.d/autostart.conf
