import QtQuick

QtObject {
    readonly property var presets: [
        {
            name: "Tela Cyan",
            pill: "#33282828",
            section: "#33121212",
            active: "#99121212",
            text: "#ffffff",
            muted: "#40ffffff",
            accent: "#b0f5e5",
            accent2: "#a4e4fe",
            bluetooth: "#f6a4fe",
            clock: "#eefff1",
            cpu: "#FE968B",
            memory: "#FFEAAA",
            window: "#e6f2d6"
        },
        {
            name: "Sakura",
            pill: "#33302734",
            section: "#3317131a",
            active: "#99543a51",
            text: "#fff7fb",
            muted: "#66fff7fb",
            accent: "#ffb3d1",
            accent2: "#c7b8ff",
            bluetooth: "#ff9fe8",
            clock: "#ffe2ee",
            cpu: "#ff8f9f",
            memory: "#ffe0a6",
            window: "#ffd6ea"
        },
        {
            name: "Mint",
            pill: "#33242d29",
            section: "#33111815",
            active: "#99446d59",
            text: "#f5fff9",
            muted: "#66f5fff9",
            accent: "#a8f7c6",
            accent2: "#9fe7d7",
            bluetooth: "#d4b7ff",
            clock: "#defee8",
            cpu: "#ff9c8c",
            memory: "#f7e7a2",
            window: "#d8f8c7"
        },
        {
            name: "Amber",
            pill: "#33342d24",
            section: "#331a1510",
            active: "#99745b2f",
            text: "#fffaf0",
            muted: "#66fffaf0",
            accent: "#ffd27d",
            accent2: "#ffc6a8",
            bluetooth: "#e8b3ff",
            clock: "#fff0c2",
            cpu: "#ff867d",
            memory: "#ffe28a",
            window: "#ffe8ad"
        },
        {
            name: "Nord",
            pill: "#33303945",
            section: "#33171c24",
            active: "#99546a86",
            text: "#eceff4",
            muted: "#669aa7bd",
            accent: "#8fbcbb",
            accent2: "#88c0d0",
            bluetooth: "#b48ead",
            clock: "#d8dee9",
            cpu: "#bf616a",
            memory: "#ebcb8b",
            window: "#a3be8c"
        },
        {
            name: "Grape",
            pill: "#332b2738",
            section: "#3315111d",
            active: "#995b4a82",
            text: "#faf5ff",
            muted: "#66faf5ff",
            accent: "#c9a7ff",
            accent2: "#9cc7ff",
            bluetooth: "#f0a6ff",
            clock: "#ddd0ff",
            cpu: "#ff8da1",
            memory: "#f4d88f",
            window: "#d6b8ff"
        },
        {
            name: "Blue",
            pill: "#33232d3a",
            section: "#33101722",
            active: "#99425f8f",
            text: "#f4f9ff",
            muted: "#66f4f9ff",
            accent: "#8ecbff",
            accent2: "#79e4ff",
            bluetooth: "#b9b6ff",
            clock: "#d8efff",
            cpu: "#ff8f9d",
            memory: "#ffe39b",
            window: "#b7dcff"
        },
        {
            name: "Purple",
            pill: "#332c2638",
            section: "#33171122",
            active: "#99624b91",
            text: "#fbf5ff",
            muted: "#66fbf5ff",
            accent: "#c59cff",
            accent2: "#a9b7ff",
            bluetooth: "#eba6ff",
            clock: "#ead8ff",
            cpu: "#ff8aa8",
            memory: "#f6d98f",
            window: "#dec0ff"
        },
        {
            name: "Green",
            pill: "#33242f28",
            section: "#33111915",
            active: "#99467455",
            text: "#f4fff7",
            muted: "#66f4fff7",
            accent: "#9cf2b6",
            accent2: "#83e6cf",
            bluetooth: "#c7b5ff",
            clock: "#d7ffe2",
            cpu: "#ff9a89",
            memory: "#f4e29a",
            window: "#c8f7b7"
        }
    ]
}
